apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3h-dep
  labels:
    app: s3h
spec:
  selector:
    matchLabels:
      app: s3h
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: s3h
    spec:
      containers:
      - image: uditopstree/devtron:s3hservice
        name: s3h
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: s3h-service
spec:
  type: NodePort
  selector:
    app: s3h
  ports:
  - protocol: TCP
    port: 8080
