apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: uditopstree/devtron:mysql1
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_DATABASE
          value: employeedb
          # - name: MYSQL_USER
          # value: root
          # - name: MYSQL_PASSWORD
          # value: password
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306

---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
